#!/bin/bash

echo "🚀 Deploying Backend to Render..."

echo ""
echo "📋 Steps to deploy your backend:"
echo ""
echo "1. Go to https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository: https://github.com/Kaushik-07/BrandRanker"
echo "5. Configure the service:"
echo "   - Name: brand-ranker-backend"
echo "   - Root Directory: backend"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "6. Add Environment Variables:"
echo "   - SECRET_KEY: your-secret-key-change-in-production"
echo "   - ALGORITHM: HS256"
echo "   - ACCESS_TOKEN_EXPIRE_MINUTES: 30"
echo ""
echo "7. Click 'Create Web Service'"
echo ""
echo "8. Wait for deployment (2-3 minutes)"
echo ""
echo "9. Copy the Render URL (e.g., https://brand-ranker-backend.onrender.com)"
echo ""
echo "10. Update frontend API URL:"
echo "    cd frontend"
echo "    echo 'REACT_APP_API_URL=https://brand-ranker-backend.onrender.com' > .env"
echo "    npm run build"
echo "    firebase deploy"
echo ""
echo "🎯 Your Firebase app will then work with authentication!" 