"""Add enhanced metadata columns to experiments table

Revision ID: ce8d57cd0a92
Revises: 
Create Date: 2025-07-29 22:37:53.445841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8d57cd0a92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('experiments', sa.Column('llm_metadata', sa.JSON(), nullable=True))
    op.add_column('experiments', sa.Column('performance_metrics', sa.JSON(), nullable=True))
    op.add_column('experiments', sa.Column('user_ip', sa.String(length=45), nullable=True))
    op.add_column('experiments', sa.Column('user_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'user_agent')
    op.drop_column('experiments', 'user_ip')
    op.drop_column('experiments', 'performance_metrics')
    op.drop_column('experiments', 'llm_metadata')
    op.drop_column('experiments', 'tags')
    # ### end Alembic commands ###
